name: Deploy Cloud Resume Challenge on dev

on:
  push:
    branches:
    - main
    paths:
    - "environmets/dev/**"

jobs:
  deploy:
    name: Deploy dev environment
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      working_dir: ./environments/dev
    secrets: inherit

  docs:
    name: Generate Terraform documentation
    uses: ./.github/workflows/documentation.yml
