name: Deploy Cloud Resume Challenge on prod

on:
  push:
    branches:
    - main
    paths:
    - "environmets/prod/**"

jobs:
  deploy:
    name: Deploy prod environment
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      working_dir: ./environments/prod
    secrets: inherit

  docs:
    name: Generate Terraform documentation
    uses: ./.github/workflows/documentation.yml
