name: Deploy Cloud Resume Challenge

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working_dir:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    name: Deploy environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_dir }}
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_domain: ${{ vars.TF_VAR_DOMAIN }}
      TF_VAR_project: ${{ vars.TF_VAR_PROJECT }}
      TF_VAR_region: ${{ vars.TF_VAR_REGION }}
    steps:
    - uses: action/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: 1.11.0

    - run: |
        terraform init
    - run: |
        terraform apply -auto-approve
