name: Deploy Cloud Resume Challenge on dev

on:
  workflow_run:
    workflows:
    - Documentation
    types:
    - completed

jobs:
  deploy-dev:
    name: Deploy dev environment
    # only run if documentation succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      working_dir: ./environments/dev
    secrets: inherit
