name: Destroy Cloud Resume Challenge on dev

on:
  pull_request:
    types:
    - closed
    branches:
    - main
    paths:
    - "environment/prod/**"


jobs:
  destroy:
    name: Destroy dev environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/dev
    # Destroy only if the pull request is merged
    if: github.event.pull_request.merged == true
    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.0

    - run: |
        terraform init
    - run: |
        terraform destroy -auto-approve
