name: Documentation

on:
  pull_request:
    paths:
    - "modules/**"
  workflow_call:

jobs:
  docs:
    name: Generate Terraform documentation
    # only run if pre-commit succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Generate docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        recursive: true
        recursive-include-main: false # it will not generate documentation at the root
        git-commit-message: "docs(terraform): generate documentation"
        git-push: true
