name: Pre-commit

on:
  pull_request:
    paths:
    - "environments/**"
    - "modules/**"

permissions:
  contents: read

jobs:
  pre-commit:
    permissions:
      contents: write # allow pre-commit/action to push fixes to PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

    - name: Get modified files
      id: file_modifications
      run: |
        DIFF=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }})
        export DIFF
        echo "Diff between ${{ github.base_ref }} and ${{ github.sha }}"
        echo "files=$( echo "$DIFF" | xargs echo )" >> "$GITHUB_OUTPUT"

    # Needed for pre-commit to fix pushes to PR
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-python@v5.4.0
      with:
        python-version: 3.13

    - uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: 1.11.0

    - uses: terraform-linters/setup-tflint@v4.1.1

    - uses: aquasecurity/setup-trivy@v0.2.3
      with:
        version: 0.61.0

    - name: Execute pre-commit
      uses: pre-commit/action@v3.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        extra_args: |
          --files ${{ steps.file_modifications.outputs.files }}

  docs:
    needs: pre-commit
    permissions:
      pull-requests: write
    name: Generate Terraform documentation
    uses: ./.github/workflows/documentation.yml
